---
- hosts: server2
  user: root
  sudo: yes
  gather_facts: yes 
  tasks:
    - name: install apache
      yum: name=httpd state=present
      notify: 
        - start apache 

  handlers:
    - name: start apache
      service: name=httpd state=started
