---
- hosts: ansibleagent
  user: root
  become: true
  gather_facts: yes
  tasks:
   - name: install apache webserver
     yum: name=httpd state=present
   - name: start the service
     service: name=httpd state=started
     register: result
   - debug: var=result      
