---
- hosts: server2
  user: root
  sudo: yes
  gather_facts: yes
  tasks:
   - name: execute the script for addition of two numbers
     script: /etc/ansible/playbooks/add.sh
     register: result
   - debug: var=result
