---
- hosts: server2
  user: root
  sudo: yes
  gather_facts: yes
  vars_prompt:
   - name: pkg
     prompt: enter package name
     private: no
  tasks:
   - name: install apache
     yum: name={{pkg}} state=present
     register: result
   - debug: var=result 
