---
- hosts: server2
  user: root
  sudo: yes
  gather_facts: yes
  tasks:
    - name: install apache in redhat flavour
      yum: name=httpd state=present
      when: ansible_os_family == "RedHat"

    - name: install apache in ubuntu
      apt: name=httpd state=present
      when: ansible_os_family == "Debian"
